name: Documentation Quality Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9 AM UTC

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Markdown Link Check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: 'mlc_config.json'

      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          config: .markdownlint.yaml
          files: '**/*.md'

      - name: Spell Check
        uses: rojopolis/spellcheck-github-actions@v0.30.0
        with:
          config_path: .spellcheck.yml
